behaviors:
  RTSAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
  # TODO: adjust the steps and numbers appropriately. Currently they are set very high for testing purposes.
  # Since the training will be redone using the previously trainined model, the numbers can be reduced.
    max_steps: 36000
    time_horizon: 300
    summary_freq: 300
    checkpoint_interval: 9000