behaviors:
  RTSAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 4096
      learning_rate: 0.0002
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
      # Try cosine
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
  # TODO: adjust the steps and numbers appropriately. Currently they are set very high for testing purposes.
  # Since the training will be redone using the previously trainined model, the numbers can be reduced.
    max_steps: 360000
    time_horizon: 400
    summary_freq: 400
    checkpoint_interval: 12000